version: "3.8"

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Qwerty_1234"
      ACCEPT_EULA: "Y"
  
volumes:
  sqlserver_data:
      
networks:
  warehouse:
    name: warehouse-network
    
    